language: node_js

# Use a similar version to that on Lambda.
node_js:
  - 6

cache:
  yarn: true
  directories:
    - node_modules

# Skip builds on version tags, as they'll occur on the branch anyway.
branches:
  except:
    - /^v[0-9]\.[0-9]\.[0-9]/

install:
  - yarn

script:
  - yarn lint
  - yarn test

deploy:
  on:
    branch: tim
  skip_cleanup: true

  # @see https://docs.travis-ci.com/user/deployment/lambda/
  provider: lambda
  function_name: "papertrail-rsync"
  region: "ap-southeast-2"
  role: "arn:aws:iam::300761597318:role/lambda_s3_bucket"
  runtime: "nodejs6.10"
  handler_name: "handler"
  access_key_id: "AKIAI2EGLBKJJUQZE3LA"
  secret_access_key:
    secure: "qViya0nTw/wUbLbClJLaMFwyZd97CEQJM+i/gWhwc4/rhjSnMV4Qr/WTgOY4syEarYhlUtJ+379vEAll8z4pVYv+wJ+3HpbMsAcIuZ3A3rgr4C4Lw0c5WkyehX15ab8QzZqxu3TkrP8CNqCEtocs2euHokc5bNbvYEAZhavDQXOvcSOssAt6kACzBq+/Q5h9yCCzoAKhVpKCPek85sFe7rzZcvJGnuJzt0QnWxTL3lBGnnoLIfNp75vzoI0r7YE4ouSSJHnpwkJURD+GrKZpCn1nucbIMHjqej3Jdel09rTK1IzZZjjktBSKvfgH401tZn8JVZr3KV7n8ce8ekysFWj74hZg+fI8+yzpi9K7yT6RNvdaa6aCQVdsbFEkSPJBiBIwTrN3dbp0Q2Py/omlZNzcB5ac0S11zXWQXwH8ekmyMES6MEuTt/ge65WI7aN4fIpGva/znc842q56TfpVodAO++O0Oj8S5+Ej4EG4errOY/CRsB7sSMVCRFmc/4Y3vkX3CLrgJGl7TfdY62Fxxhj8tpxXK22zX0FDDF7yM0QlF4X07DF3RgLvtgwtX0OlsFZSGT6cUZC4ubNAoUw+9hOCS5MFXTyrMNzf55dQSKSmcdmRL4alrXOR+daaReNgpKxIeN6/IoPTL03Wvv+bzZz973JgXIK2L+r2BrFQSik="

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
