language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAIETZ7UTECKLYJJYQ
    - AWS_DEFAULT_REGION=ap-southeast-2
    - LAMBDA_NAME=sftpToPapertrail
    - LAMBDA_ALIAS=prod

    - STP_SFTP_HOST=appserver.dev.aea704e1-f89f-4a49-a160-c0d9a71c4671.drush.in
    - STP_SFTP_PORT=2222
    - STP_SFTP_USERNAME=dev.aea704e1-f89f-4a49-a160-c0d9a71c4671
    - STP_SFTP_PATH=logs/nginx-access.log,logs/nginx-error.log,logs/php-fpm-error.log,logs/php-slow.log
    - STP_S3_BUCKET=aws-admin-timmalone
    - STP_PAPERTRAIL_HOST=logs5.papertrailapp.com

    # STP_SFTP_PASSWORD
    - secure: RK11+6XQmexZeCAaIDoJ5/bdMRfptsj2Pqgfd9qIs6EIai+N133OnGPpOqnIDbwd9MV3U/yfjfp4N+HqIgl6BHV9gr8Lg9DK16+6nY7j9dxeV6izDSE8JvA2EahBKtU+Ir06J/0pGwMd06XLh8GFRA+dMUOJ02nD4fS01MUxNlPThuF31u2nPcoZfcpxpGpWDcuH/KprlzL1oUMjDmuu2H4Fz1Oi+gffECVg01tO6gDu1y3swXFf3qDEB1SJKN74QKmli1byZsdKox3no3f02ZDhZp4gABBOROVYz5Tzy0tBq++6Qbj84ZUD00xu+Fv1lXAozKFJILDI/KOdfCg8zCm0K6IQPCensz/GWiU4N6NESmedcFc4c2Fpm/LfNkcCSW2y7BQ0f7x7KK+wpe1PzCl0lN9p4Wc3vkrvOJYLZ99GdACDaJcpbS8EaTIF7p8kUiP3cnJBY+5n9N4j4r3+zdl3fDgS0Tm8sM1OIjQRKWECo6/++EA9XSt49xUXfj4VWB+eEJqWdDafVtSlFFub5j+he+HC5kCbLG5MvO8EzDgK76uDVjFH+SIydxFCymW6Js4jAy8J9kYQ8hVHSyv1EAXhiadIWcwcMANUOnNj3DA6zP0sKF3U1E4AJYj4RsjXNgGUxCaVERIGEYCDjGy3EHjEdnb/NpsfLZ0mqpyNpUE=

    # STP_PAPERTRAIL_PORT
    - secure: q2/lFQ6cAJQNmJGACMJgmN5SbgcpMPd7jAIt6I6c09LSSc4aiSOlFdSJsGL8CfbdBf1Tv2YwuBFPTzYxEhOkeeOKQAbX4daqFtuwKHsZg12w4AnrItkyx6OXUJnruX8pjpbxQl0IX92szget4GTG/fpmVWeWZ1z7wT6WwL1aVF8jOKtPrPytzMjh7lSgkha0PmfDDB4eLq0vIosftn4ashBfmai69nhtj6OJyzAtx9DdJIzx1DI4BoPdi+Sjs+rJiysjdTvbQvK9aGa7QloKMvkW6qiK0W6hZl7WYF7qmat4qOvzFCChffJ/OJbHMloDb3qZru3BTn+HOTXSHz/NevGs6/EWOYtDEewYjrwdW12O+jqJhR6VG0L4+prDvTxogYXJsDOpk9BUj1CKK7fBaVKd7EhDcAMF12g+08REwb7j98yBtPwfQrE92ZnQqkPLwxfJZQoegop76lqOLN5SDbljLsjgNBlQKaluXp+3bCaTLJ9j80bNoUd7jX1vyLr2RXSdXB9ds7baXJtiIOOjnCGtNOnoJB5cHO62nsEkNWs3cQrlckStENI6xDoWz6sGDPpe90unZ3j+UMTP9nUkXnmI87PsOzF5dCkRwMu5Ea0I4fCwnyeuZZ7AJ+hDjDuhQPE7l3OpDwRujKNdpHd9cHgcgPlPmrztaCAUlTqvpEw=

    # AWS_SECRET_ACCESS_KEY
    - secure: ViadDnPh5cylNXx/W+jiSTCOflzfx5vYprZhjjB8Oxibud6b78VpaijBkuW5vSg55Daqm0Br0unmx+3Bu/Yf+NUwtO2m6QJSp+lioJ9ect2lUdBkif/T/OyKFvBe24yNiqVuITZvKZUABVo187N78HYVe34cU4e0w+WSJuMfAy1hx7l9eBdMOqlOWdu+9qYqitimvN0RmluSWf9iCI8a8cDxaE6h+bAZqIwVewwIuek2LrkJbTffKSCikbD8QaSNhUdm/Vpo9mumhegHSFnJYB4pWHOtVoq+aTx3w19hqO0/V+QaZstnBFEtWQDg5qj1GM6jc9jbl/YmEOK46Ng3oUU9SZOJZAkbGzchYSQrfb8mNr676qmH+63yrk1VlpA725YImdgBIAY3WKtlQcwsrrvUwK7hHH+698ZCkFl7xMtGjSPVCxuTh+Y+t8q++ZFF/cFvWfgVfl+gA/Z0iBpOoR+wdHpYdOqIhW1f0yBjQORleg5XOz7Qv5fNRLBm/2J4mZdirVlbVOFfbG7A0Z+2bUge15qdH7aFmRYxmpMqfQaNE6FXuXIJKc7UNRMMBnsWpGxVtEI0oUvwb5ZE271COfKGbyehT0lglkdTDwgk0w5b8OaIkTnvajKSR1mpo+bpZOwOkEVeMpWBNr91wRA6FdjnpOwFID4l4n7N1xFemWA=

cache:
  yarn: true
  directories:
    - node_modules

install: yarn

script:
  - yarn lint
  - yarn test

before_deploy: rm -rf node_modules && yarn --prod && rm -rf tests .*rc.js
before_deploy: yarn remove aws-sdk && rm -rf coverage node_modules tests .*rc.js && yarn --prod

before_deploy:

  # Keep Lambda function size down by removing what we don't need.
  - if [ "$HAVE_WE_ALREADY_DONE_THIS" != "true" ]; then
      yarn remove aws-sdk;
      rm -rf node_modules;
      yarn --prod;
      rm -rf coverage tests .*rc.js .gitignore LICENSE package.json *.md *.lock;
      export HAVE_WE_ALREADY_DONE_THIS=true;
    fi

deploy:

  # @see https://docs.travis-ci.com/user/deployment/lambda/

  - on:
      branch: chromatix
    skip_cleanup: true

    provider: lambda
    publish: true
    function_name: sftpToPapertrail-nomosOne
    region: ap-southeast-2
    role: arn:aws:iam::300761597318:role/genericLambdaRole
    runtime: nodejs6.10
    timeout: 120
    handler_name: handler
    description: Retrieves log files via SFTP, and logs new entries to Papertrail.
    access_key_id: AKIAIY72BYOTX7AYCKAA
    secret_access_key:
      secure: HRe/p/2FCiAqCMIzjfYTpIPg0pt1a7GQw5Zj7eU9N1wN6UMC4SsrWnsd3HV2RZdAOA4jMkwnIcUmCvmrUdSa+7ZymdjZOZCIwAWUBRgCbH79oCqywqMUIQdqJdRBEQuSjMxkmuSINo0+xO4kA1Tg20mE6C2Y8z44F0hfVK9hHNwZADwrg/kmyNRSNZZHgvfNqF0WfRC49sC9V71AvywSnVyHGNc3Qv1f+fX38QJmEm5Pr8Po9A92WL7hga2FUi//ubrAEopXJpbXtjXiT/sfV8m4HFMRa3/+ivhHjNcVvHPiR3bzcKHvF+/6T+WnuwYsVXmST0mmWfqQ02D5YTx9n0jgYlpEwWmX5q1mj+cqdsINPNbQ5kRt2nY08Au6HZSZllnMyFZanx2a72v+zpOREKFEBoVmyZ05s1fJUo7z4WSEACDaKskk9eHuo6aM3LvXICQRyVN81CIYH/KW0/m19uK16C++v/osjjAWT1xLyI4ELEReyYDkkRhhpvhBTGGh9SBA4Wu97y6jyJQ0taIqqMgjhTTcCWfvWWWR64NlVndU9vn/aDVWfpNN0DRYcDLLE5Gr2r2XDnDfP+omKNgsKO0Y5IsH1gRxTSC4mRSl1vRp8GSA7L3r55XVzs4ATf/KMjoVdzrn8fhjUXctWQQPvruDpLgIuxoJEOEdYwis5rU=

  - on:
      branch: chromatix
    skip_cleanup: true

    provider: lambda
    publish: true
    function_name: sftpToPapertrail-intendedWealth
    region: ap-southeast-2
    role: arn:aws:iam::300761597318:role/genericLambdaRole
    runtime: nodejs6.10
    timeout: 120
    handler_name: handler
    description: Retrieves log files via SFTP, and logs new entries to Papertrail.
    access_key_id: AKIAIY72BYOTX7AYCKAA
    secret_access_key:
      secure: HRe/p/2FCiAqCMIzjfYTpIPg0pt1a7GQw5Zj7eU9N1wN6UMC4SsrWnsd3HV2RZdAOA4jMkwnIcUmCvmrUdSa+7ZymdjZOZCIwAWUBRgCbH79oCqywqMUIQdqJdRBEQuSjMxkmuSINo0+xO4kA1Tg20mE6C2Y8z44F0hfVK9hHNwZADwrg/kmyNRSNZZHgvfNqF0WfRC49sC9V71AvywSnVyHGNc3Qv1f+fX38QJmEm5Pr8Po9A92WL7hga2FUi//ubrAEopXJpbXtjXiT/sfV8m4HFMRa3/+ivhHjNcVvHPiR3bzcKHvF+/6T+WnuwYsVXmST0mmWfqQ02D5YTx9n0jgYlpEwWmX5q1mj+cqdsINPNbQ5kRt2nY08Au6HZSZllnMyFZanx2a72v+zpOREKFEBoVmyZ05s1fJUo7z4WSEACDaKskk9eHuo6aM3LvXICQRyVN81CIYH/KW0/m19uK16C++v/osjjAWT1xLyI4ELEReyYDkkRhhpvhBTGGh9SBA4Wu97y6jyJQ0taIqqMgjhTTcCWfvWWWR64NlVndU9vn/aDVWfpNN0DRYcDLLE5Gr2r2XDnDfP+omKNgsKO0Y5IsH1gRxTSC4mRSl1vRp8GSA7L3r55XVzs4ATf/KMjoVdzrn8fhjUXctWQQPvruDpLgIuxoJEOEdYwis5rU=

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
