language: node_js
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAIY72BYOTX7AYCKAA
    - AWS_DEFAULT_REGION=ap-southeast-2
    - LAMBDA_ROLE=arn:aws:iam::300761597318:role/genericLambdaRole
    - LAMBDA_RUNTIME=nodejs6.10
    - LAMBDA_TIMEOUT=120
    - LAMBDA_DESCRIPTION="Retrieves log files via SFTP, and logs new entries to Papertrail."

    # AWS_SECRET_ACCESS_KEY
    - secure: H3IOtsGE7Z/ONTlxqBqc0raByh1lfDIR9aa6XBB6xj8Ini4pltJsk9EcSLc+djxXwJl4EcdhOlOgdhVcWVd5EufsirBZuH92WlUxx0IBCDLC90eLHNuQUMWEZ03VEwhk2ws9X10KuLpEo8Xb+kN1vDVpAcrGe2RGqbFShNWjw0Flp0sZ2czKwyVvAWmyRKt8o3Zga9cedX9W51ngA6UpU+gXwcDgjvwGLsxr8lA44TOpctKw5umqI0TjUjszlk4GVbSrnLu0SMU9cswKOOuUPOqAbqLTpXbE4unNhnZP4zi+JIwViMdfPSDGKD7fjPgyxpTsPSdXuAW/um9+S+OjO59XAmtmAvCRXYjhkNDM+yQBS6XBOdWFBf57emBgfQ1YMjxly2qD/qxQA2kIhWiKjDQ0kRaBAHFYZEOQnL1PFSAPUFpyt1jlYmjQsY1T4lSiqHEqJOB0pSPJS+n+Vru1X8tdDYZZgvFjwnNvO9Seo81FADiVisPqF6fYwe7XXtycxrR/+ys4BY54W1Zm/+t4RhfcajbDLEkqTGAgakXzDLaAPZs1Ouf5DcT0X0SooMMopfBDeDsltEXdYc+Dkrtv67RNLJtVjosgFHckrFRmmuROKbzWI/jRGxpvmud3mVw1LEa7+sIhVZcVei9g6yxB82yScY2g7AVDNRLdxDi4VJg=

cache:
  yarn: true
  directories:
    - node_modules

# Skip builds on version tags, as they'll occur on the branch anyway.
branches:
  except:
    - /^v[0-9]\.[0-9]\.[0-9]/

install: yarn

script:
  - yarn lint
  - yarn unit-tests

before_deploy:

  # Keep Lambda function size down by removing what we don't need.
  - if [ "$HAVE_WE_ALREADY_DONE_THIS" != "true" ]; then
      yarn remove aws-sdk;
      rm -rf node_modules;
      yarn --prod;
      rm -rf coverage tests .*rc.js .gitignore LICENSE package.json *.md *.lock;
      export HAVE_WE_ALREADY_DONE_THIS=true;
    fi

deploy:

  # @see https://docs.travis-ci.com/user/deployment/lambda/

  - on:
      branch: chromatix
    skip_cleanup: true

    provider: lambda
    publish: true
    function_name: sftpToPapertrail-nomosOne
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    handler_name: handler
    description: $LAMBDA_DESCRIPTION
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY

  - on:
      branch: chromatix
    skip_cleanup: true

    provider: lambda
    publish: true
    function_name: sftpToPapertrail-intendedWealth
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    handler_name: handler
    description: $LAMBDA_DESCRIPTION
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
